shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/ni': ^30.1.0
    '@eslint/config-inspector': ^3.0.4
    bumpp: ^11.1.0
    lint-staged: ^16.2.7
    obuild: ^0.4.36
    simple-git-hooks: ^2.13.1
    tsx: ^4.22.4
    typescript: ^5.9.3
    vite: ^7.3.1
  peer:
    '@antfu/eslint-config': ^9.0.0
    eslint: ^9.39.3
    eslint-plugin-format: ^2.0.1
  prod:
    eslint-flat-config-utils: ^3.2.0
  testing:
    vitest: ^4.1.8
    vitest-package-exports: ^1.2.0
    yaml: ^2.9.0
  types:
    '@types/node': ^22.19.15
  utils:
    tinyexec: ^1.2.4

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
